---
title: "Final Coding Challenge"
author: "Joseph Borjon"
date: "July 19, 2018"
output:
  html_document:
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 12
    fig_width: 12
    fig_align: "center"
---
  
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r wrangle}
library(tidyverse)
marathons <- read_csv("https://www.dropbox.com/s/wq9e3wqzow500uo/master_marathon.csv?dl=1")
```

## The Charts

May I just say, I experienced some technical difficulties (I tried to plot each point, and my computer crashed twice) that stole about 20 minutes from me. I'm still proud of what I've accomplished.

```{r nytimes_plot}
# NY Times plot
marathons %>%
  ggplot() +
  geom_histogram(
    aes(chiptime),
    binwidth = 1,
    fill = "#eeeeee"
  ) +
  labs(
    title = "Distribution of marathon finishing times",
    subtitle = "The small spikes are people making their goals, with not a minute to spare.\nA finishing time of 3:59 is 1.4 times as likely as one of 4:01.",
    x = "Time (minutes)",
    y = "Number of finishing times",
    caption = "Based on data from Eric Allen, USC, Patricia Dechow, U.C. Berkeley, Devin Pope and George Wu, University of Chicago."
  ) +
  coord_cartesian(xlim = c(120, 420)) +
  scale_y_continuous() +
  theme_light() +
  theme(
    text = element_text(
      size = 11,
      family = "Franklin Gothic Book"
    )
  )
```

```{r time_vs_age}
# Runner time vs. age
marathons %>%
  ggplot(aes(chiptime, age)) +
  geom_smooth(color = "#f8d568", fill = "#81d8d0") +
  labs(
    title = "As runner age increases, so does finishing time",
    subtitle = "This was originally going to be a scatterplot, which made my machine crash. Twice.",
    x = "Finishing time (minutes)",
    y = "Runner age"
  ) +
  theme_light() +
  theme(
    text = element_text(
      size = 11,
      family = "Franklin Gothic Book"
    )
  )
```

```{r gender}
# Count of males vs females
marathons %>%
  filter(!is.na(gender)) %>%
  ggplot(aes(gender)) +
  geom_bar(fill = "#81d8d0") +
  labs(
    title = "There were about twice the number of males as females in the marathons",
    x = "Gender",
    y = "Count"
  ) +
  theme_light() +
  theme(
    text = element_text(
      size = 11,
      family = "Franklin Gothic Book"
    )
  )
```
